package org.example.app.util;

public class Options {
    public final static String[] ZIVILSTAND = {
            "ledig",
            "verheiratet",
            "verwitet",
            "geschieden",
            "getrennt",
            "eingetragene Partnerschaft",
            "aufgeloste Partnerschaft"
    };

    public final static String[] KONFESSION = {
            "reformiert",
            "romisch-katholisch",
            "christ-katholisch",
            "andere",
            "keine"
    };

    public final static String[] GEMEINDE = {
            "Adlikon",
            "Adliswil",
            "Aesch",
            "Aeugst am Albis",
            "Affoltern am Albis",
            "Altikon",
            "Andelfingen",
            "Bachenbülach",
            "Bachs",
            "Bassersdorf",
            "Bauma",
            "Benken",
            "Berg am Irchel",
            "Birmensdorf ZH",
            "Bonstetten",
            "Boppelsen",
            "Brütten",
            "Bubikon",
            "Buch am Irchel",
            "Buchs ZH",
            "Bäretswil",
            "Bülach",
            "Dachsen",
            "Dielsdorf",
            "Dietikon",
            "Dietlikon",
            "Dinhard",
            "Dorf",
            "Dägerlen",
            "Dällikon",
            "Dänikon",
            "Dättlikon",
            "Dübendorf",
            "Dürnten",
            "Egg",
            "Eglisau",
            "Elgg",
            "Ellikon a.d. Thur",
            "Elsau",
            "Embrach",
            "Erlenbach ZH",
            "Fehraltorf",
            "Feuerthalen",
            "Fischenthal",
            "Flaach",
            "Flurlingen",
            "Freienstein-Teufen",
            "Fällanden",
            "Geroldswil",
            "Glattfelden",
            "Gossau ZH",
            "Greifensee",
            "Grüningen",
            "Hagenbuch",
            "Hausen am Albis",
            "Hedingen",
            "Henggart",
            "Herrliberg",
            "Hettlingen",
            "Hinwil",
            "Hittnau",
            "Hochfelden",
            "Hombrechtikon",
            "Horgen",
            "Humlikon",
            "Höri",
            "Hüntwangen",
            "Hüttikon",
            "Illnau-Effretikon",
            "Kappel am Albis",
            "Kilchberg ZH",
            "Kleinandelfingen",
            "Kloten",
            "Knonau",
            "Küsnacht ZH",
            "Langnau am Albis",
            "Laufen-Uhwiesen",
            "Lindau",
            "Lufingen",
            "Marthalen",
            "Maschwanden",
            "Maur",
            "Meilen",
            "Mettmenstetten",
            "Männedorf",
            "Mönchaltorf",
            "Neerach",
            "Neftenbach",
            "Niederglatt",
            "Niederhasli",
            "Niederweningen",
            "Nürensdorf",
            "Oberembrach",
            "Oberengstringen",
            "Oberglatt",
            "Oberrieden",
            "Oberweningen",
            "Obfelden",
            "Oetwil am See",
            "Oetwil a.d. Limmat",
            "Opfikon",
            "Ossingen",
            "Otelfingen",
            "Ottenbach",
            "Pfungen",
            "Pfäffikon ZH",
            "Rafz",
            "Regensberg",
            "Regensdorf",
            "Rheinau",
            "Richterswil",
            "Rickenbach ZH",
            "Rifferswil",
            "Rorbas",
            "Russikon",
            "Rümlang",
            "Rüschlikon",
            "Rüti ZH",
            "Schlatt",
            "Schleinikon",
            "Schlieren",
            "Schwerzenbach",
            "Schöfflisdorf",
            "Seegräben",
            "Seuzach",
            "Stadel",
            "Stallikon",
            "Stammheim",
            "Steinmaur",
            "Stäfa",
            "Thalheim a.d. Thur",
            "Thalwil",
            "Truttikon",
            "Trüllikon",
            "Turbenthal",
            "Uetikon am See",
            "Uitikon",
            "Unterengstringen",
            "Urdorf",
            "Uster",
            "Volken",
            "Volketswil",
            "Wald ZH",
            "Wallisellen",
            "Wangen-Brüttisellen",
            "Wasterkingen",
            "Weiach",
            "Weiningen ZH",
            "Weisslingen",
            "Wettswil am Albis",
            "Wetzikon ZH",
            "Wiesendangen",
            "Wil ZH",
            "Wila",
            "Wildberg",
            "Winkel",
            "Winterthur",
            "Wädenswil",
            "Zell ZH",
            "Zollikon",
            "Zumikon",
            "Zürich"
    };
}
